"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_VALUE = config('DJANGO_SECRET_KEY')
SECRET_KEY = SECRET_KEY_VALUE


# Application definition
INSTALLED_APPS = [
    # 'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'task',
    'rest_framework',
    'corsheaders',
  
]


# Specify the ASGI application
ASGI_APPLICATION = 'root.wsgi.application'

# Configure the channel layers


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    # 'htmlmin.middleware.HtmlMinifyMiddleware',
    # 'htmlmin.middleware.MarkRequestMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]


ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS=[os.path.join(BASE_DIR, "static")]

WHITENOISE_MANIFEST_STRICT = False


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS= True

# expires: Datetime has wrong format. Use one of these formats instead: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].


ALLOWED_HOSTS = ['*']


DEBUG = True
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # One year in seconds
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE= False
    CSRF_COOKIE_SECURE=True
    SECURE_HSTS_SECONDS=3600
    SECURE_SSL_REDIRECT=True
    SECURE_HSTS_INCLUDE_SUBDOMAINS =True
    SECURE_HSTS_PRELOAD =True   
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    SESSION_COOKIE_AGE = 3600

     
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ADMINS=[("emmanuel", "emmanuel47peters@gmail.com")]
MANAGERS=[("emmanuel", "emmanuel47peters@gmail.com")]




RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    SESSION_COOKIE_SECURE= True
    CSRF_COOKIE_SECURE=True
    SECURE_HSTS_SECONDS=3600
    SECURE_SSL_REDIRECT=True
    SECURE_HSTS_INCLUDE_SUBDOMAINS =True
    SECURE_HSTS_PRELOAD =True
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    DATABASE_URL= config('DATABASE_URL')
    DATABASES = {'default':dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
else:
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }
    DATABASE_URL= config('DATABASE_URL')
    DATABASES = {'default':dj_database_url.parse(DATABASE_URL, conn_max_age=600)}

cloudinary.config( 
  	cloud_name = config('CLOUD_NAME'),
  	api_key = config('API_KEY'),
  	api_secret = config('API_SECRET'),
    secure = True 
)