# Generated by Django 5.0.3 on 2024-03-16 13:51

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('expires', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField()),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished')], default='Started', max_length=100)),
                ('contributors', models.TextField(max_length=100)),
                ('tasks_number', models.IntegerField()),
                ('image', models.ImageField(default='/tasks/cover.jpg', upload_to=task.models.upload_to)),
            ],
        ),
    ]
